name: ecs-sehi
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Scientific Stack
  - python=3.11
  - numpy>=1.24.3
  - pandas>=2.0.3
  - scipy>=1.11.1
  - scikit-learn>=1.3.0
  
  # Visualization
  - plotly>=5.18.0
  - matplotlib>=3.7.1
  
  # Jupyter & Interactive
  - streamlit>=1.28.0
  - ipykernel
  
  # Audio & Video
  - opencv
  - pyaudio
  - moviepy
  
  # Quantum Computing
  - qiskit-terra>=0.24.1
  - qiskit-aer>=0.12.0
  
  # Development Tools
  - pytest>=7.4.0
  - black>=23.3.0
  - flake8>=6.0.0
  
  # Additional packages via pip
  - pip
  - pip:
    - streamlit-ace>=0.1.1
    - streamlit-camera-input-live>=0.2.0
    - streamlit-drawable-canvas>=0.9.2
    - python-dotenv>=1.0.0
    - openai>=1.3.0
    - anthropic>=0.5.0
    - SpeechRecognition>=3.10.0
    - qiskit-ibm-runtime>=0.11.0
    - httpx>=0.24.0  # For Perplexity API
    - asyncio>=3.4.3 