[theme]
primaryColor = "#8257E5"  # Modern purple
backgroundColor = "#1E1E2E"  # Deep space purple
secondaryBackgroundColor = "rgba(255, 255, 255, 0.03)"  # Ultra-subtle white
textColor = "#E2E8F0"  # Soft white
font = "Inter"  # Modern sans-serif

[server]
port = 8502
address = "localhost"
enableCORS = true
enableXsrfProtection = true

[browser]
serverAddress = "localhost"
serverPort = 8502
gatherUsageStats = false